/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();

// start animation!
skycons.play();

// want to change the icon? no problem:
//skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);


//自動更新選單內城市的溫度資料
$('#dropdown li').each(function(index, element) {
    var city = $(this).attr("id");
    var url = 'https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D"' + city + '")&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys';
    $.getJSON(url, function(data) {
        var currentTemp = data.query.results.channel.item.condition.temp;
        temp = celsius(currentTemp);
        $(element).text($(element).text() + "  " + temp + "℃");
    });
});

//點擊表單之後要
$(function() {
    findCity('taipei');//開啟頁面時顯示台北市資訊
    $('#dropdown li').on('click', function() {
        $('button').text($(this).text());//換按鈕上的文字
        findCity($(this).attr("id"));//依照li 的id 去搜尋城市資訊，並更新到表格內
    });
});

//抓取城市資訊，並填入表格
var findCity = function(city) {
    $.getJSON(
        'https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D"' + city + '")&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys', {},
        //宣告每個會用到的變數
        function(data) {
            var currentTemp = data.query.results.channel.item.condition.temp;
            var currentDate = data.query.results.channel.item.forecast[0].date;
            var currentCond = data.query.results.channel.item.condition.text;
            var secondDate = data.query.results.channel.item.forecast[1].date;
            var secondHightemp = data.query.results.channel.item.forecast[1].high;
            var secondLowtemp = data.query.results.channel.item.forecast[1].low;
            var secondCond = data.query.results.channel.item.forecast[1].text;
            var thirdDate = data.query.results.channel.item.forecast[2].date;
            var thirdHightemp = data.query.results.channel.item.forecast[2].high;
            var thirdLowtemp = data.query.results.channel.item.forecast[2].low;
            var thirdCond = data.query.results.channel.item.forecast[2].text;
            var fourthDate = data.query.results.channel.item.forecast[3].date;
            var fourthHightemp = data.query.results.channel.item.forecast[3].high;
            var fourthLowtemp = data.query.results.channel.item.forecast[3].low;
            var fourthCond = data.query.results.channel.item.forecast[3].text;

            //更新當天資訊
            $('.temperature').text(celsius(currentTemp));
            $('.date').text(currentDate);
            $('.cond').text(currentCond);

            //更新後三天資訊
            $("thead > tr >th:nth-child(1)").text(secondDate);
            $(".temp:nth-child(1)").text(celsius(secondLowtemp) + '~' + celsius(secondHightemp) + "℃");
            $("thead > tr >th:nth-child(2)").text(thirdDate);
            $(".temp:nth-child(2)").text(celsius(thirdLowtemp) + '~' + celsius(thirdHightemp) + "℃");
            $("thead > tr >th:nth-child(3)").text(fourthDate);
            $(".temp:nth-child(3)").text(celsius(fourthLowtemp) + '~' + celsius(fourthHightemp) + "℃");

            //決定要用的icon
            skyconsDecide("today", currentCond);
            skyconsDecide("day1", secondCond);
            skyconsDecide("day2", thirdCond);
            skyconsDecide("day3", fourthCond);
        }
    );
};





//華氏、攝氏溫度轉換
var celsius = function(temp) {
    return Math.round(((temp - 32) * 5) / 9);
};

//判斷要用哪一個天氣的icon
var skyconsDecide = function(date, status) {
    if (status.search("Sunny") >= 0) {
        skycons.set(date, Skycons.CLEAR_DAY);
    }
    else if (status.search("Partly Cloudy") >= 0) {
        skycons.set(date, Skycons.PARTLY_CLOUDY_DAY);
    }
    else if (status.search("Cloudy") >= 0) {
        skycons.set(date, Skycons.CLOUDY);
    }
    else if (status.search("Rain") >= 0) {
        skycons.set(date, Skycons.RAIN);
    }
      else if (status.search("Shower") >= 0) {
        skycons.set(date, Skycons.RAIN);
    }
    else if (status.search("Windy") >= 0) {
        skycons.set(date, Skycons.WIND);
    }
    else if (status.search("Snow") >= 0) {
        skycons.set(date, Skycons.SNOW);
    }
    else if (status.search("Foggy") >= 0) {
        skycons.set(date, Skycons.FOG);
    }
    else if (status.search("Thunderstorms") >= 0) {
        skycons.set(date, Skycons.RAIN);
    }
};